### ISSUE TITLE
Add more fields to "Lab"

### ISSUE THREAD

**Issue by amschaal** [amschaal/glims#1]
Currently only Name and Description are available.  Should there be contact information, etc?

**Comment by monicabritton** [comment]
1. Add URL link?  It's been recommended that we include the lab website in the description, but currently that's only text and isn't "clickable".
2. Include field for university?  Eventually, we will have multiples of surnames, so just "Li lab" won't be sufficient.  I just did one with "LastName, Initial UCD".  Maybe we should enforce a uniform naming scheme, by having a form to fill out with fields for first and last names, email address, URL, etc.

**Comment by monicabritton** [comment]
Just notice another thing ... if the description is filled out with multiple lines (i.e., new lines), they are merged together after saving (although still separate lines if I go back into Edit mode).  Can the new lines be preserved?

**Comment by monicabritton** [comment]
I now think there should be a separate field/column for email address, rather than having it buried in the description.  (URL too.)

It would also be good to have a separate searchable field for "lab contacts" or such (although I can put them in the "Description".  For example, with many labs, I'm not dealing directly with the PI, but with one or more of the grad students, postdocs, etc.  Actually, what would really be good is to have something akin to a "contact list" that I could use to associate people with specific labs, and then be able to note when they've left.

**Comment by msettles** [comment]
Last Name, First Name, Affiliation, Lab link (but not required)
Auto-generate the slug, Last_First_Affiliation or something like that

**Comment by amschaal** [comment]
Split name into first/last.  Last name is required and used if not a person.  "Slugs" are now automatically generated to be LAST_FIRST, removing special characters and replacing spaces with underscores.  Changes will land on the test server later today.
